### ISSUE TITLE
Índice de curso e blocos

### ISSUE THREAD

**Issue by Gabz01** [EduardoKrausME/moodle-theme_degrade#19]
Olá,

Ao utilizar do tema degrade, estou enfrentando essas situações ao tentar abrir ou fechar as abas de "índice de curso" e" abrir gaveta de blocos" em um curso.
Está sem ação e gerando erro no devtools.

Erro gerado no devtools:

Uncaught Error: no such method 'hide' for tooltip widget instance
    at Function.error (jquery-3.7.1.min.js:2:2741)
    at HTMLButtonElement.<anonymous> (jquery-ui.min.js:5:2067)
    at Function.each (jquery-3.7.1.min.js:2:3129)
    at ce.fn.init.each (jquery-3.7.1.min.js:2:1594)
    at V.fn.<computed> [as tooltip] (jquery-ui.min.js:5:1951)
    at Drawers.openDrawer (first.js:5002:6271)
    at Drawers.toggleVisibility (first.js:5002:8896)
    at HTMLDocument.<anonymous> (first.js:5002:11941)
    

https://github.com/user-attachments/assets/b3c79262-055b-4df6-8ed7-878388844e2c

**Comment by eduardokraus** [comment]
não consegui reproduzir o problema
